### PR TITLE
fix optimizeSelection right mouse click bug

### LINKED ISSUE #90: optimizeSelection option cannot copy the selection with the right mouse button
I think that non-left click should be judged in the mousedown callback, without triggering the customized selection logic

https://github.com/otakustay/react-diff-view/blob/43727630363f37c35c8f3dcb602a995f2f8e635d/src/Diff/index.js#L28

### PR DESCRIPTION
**Pull request by colorpeach**
Fixes #90

### CODE REVIEW

File: src/Diff/index.js [hunk 1]
```diff
@@ -25,7 +25,11 @@ const setUserSelectStyle = (element, selectable) => {
 const Diff = props => {
     const root = useRef(null);
     const enableColumnSelection = useCallback(
-        ({target}) => {
+        ({ target, button }) => {
```
Comment (otakustay) [inline src/Diff/index.js:28]: Thanks for this great PR, however to align with our coding style, you have to remove spaces inside  and modify it to`({target, button}) => {`

Comment (colorpeach) [reply src/Diff/index.js]: @otakustay done

**Comment by otakustay** [comment]
Published as `2.4.4`
